name: TF - App Deploy
run-name: ${{ inputs.terraform-apply == 'true' && 'Apply'|| 'Plan' }} TF deploy on ${{ inputs.environment }} environment

on:
    workflow_call:
      inputs:
        environment:
          description: "GCP environment to deploy"
          type: string
          required: true
        terraform-apply:
          description: "Execute a Terraform apply ('true' or 'false')"
          type: string
          default: "false"
  
        working-directory:
          description: "Directory where the terraform commands will be run (in other words: where your root tf code is hosted)"
          type: string
          required: false
          default: ./infra
        environment-file-path:
          description: "Path where the environment files are stored"
          type: string
          required: false
          default: .github/workflows/env


jobs:
    terraform:
      runs-on: ["self-hosted", "linux"]
      environment: ${{ inputs.environment }}
      concurrency: ${{ inputs.environment }}
      defaults:
        run:
          shell: bash
          working-directory: ${{ inputs.working-directory }}
          
      permissions:
        contents: "read"
        id-token: "write"
        pull-requests: write
      env:
        TF_CLOUD_ORGANIZATION: "northStar-org"
        TF_CLOUD_HOSTNAME: "terraform-awe.north-star.com"